CREATE DATABASE tubular;

GRANT ALL PRIVILEGES ON tubular.* TO 'tubular_migrate'@'%' IDENTIFIED BY 'INSERT PASSWORD HERE';
GRANT SELECT ON tubular.* TO 'tubular'@'%' IDENTIFIED BY 'INSERT PASSWORD HERE';
GRANT INSERT ON tubular.* TO 'tubular'@'%' IDENTIFIED BY 'INSERT PASSWORD HERE';
GRANT UPDATE ON tubular.* TO 'tubular'@'%' IDENTIFIED BY 'INSERT PASSWORD HERE';
GRANT DELETE ON tubular.* TO 'tubular'@'%' IDENTIFIED BY 'INSERT PASSWORD HERE';